### ISSUE TITLE
Project Proposal needed

### ISSUE THREAD

**Issue by docligot** [apolbernardo/paper_1#1]
Hi Apol, 

Let's boot up this project!

Given your chosen dataset (Mental Health in Tech) https://data.world/quanticdata/mental-health-in-tech-survey

Let's come up with some possible project directions:

- Objective/Problem statement
- Current uses/status of the data
- Related studies that use this data
- User/author expectations

Let's edit this into the readme.md file of the repository. (use the ## to denote section headings)

Note: for all changes, let's observe the following:

- Create a branch on Github for Windows and name it based on issue/task being addressed (e.g. creating project proposal)
- Do the edits on your local machine (e.g. editing readme.md)
- Once done, commit the edits, then push to the branch
- Create a pull request to merge the branch into main
- Pull request will require approval, which I will do based on evaluation of the task
- Once approved, changes are brought to main

If you have any questions/clarifications - you can always chat here on issues.

**Comment by apolbernardo** [comment]
ilan po RRL ang need for local and foreign and how old the RRL po ang acceptable.

**Comment by docligot** [comment]
Depends. Right now maybe we can start with 5-10 related papers? 

We can use some existing AI to find papers like [Consensus](https://consensus.app/)

But let's get used to splitting the task into new branches like for these bullets:

- Objective/Problem statement
- Current uses/status of the data
- Related studies that use this data
- User/author expectations

Can be 4 different branches and 4 different pull requests

Basta sundan mo yung sequence sa taas. (Branch, Edit, Commit, Push, Pull Request)

**Comment by apolbernardo** [comment]
I might change the dataset since may nakita po ako mas updated this dataset year 2017 - 2021. paki check na lang po doc if its okie po https://data.mendeley.com/datasets/mmnzx4w8cg/1 salamat po

**Comment by docligot** [comment]
Looks similar to the previous one, but I'm fine if you want to use this

**Comment by docligot** [comment]
Closing this issue. We can refine the readme with the details of the data. Will advise on next issue.
